### PR TITLE
Fix #10524 Pagination issue from Antd

### PR DESCRIPTION
**Pull request by wmzhong**
Fix the issue below:

Once 'total' is 0, 'current' in 'onShowSizeChange' is 0, which is not correct.

### CODE REVIEW

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design/issues/10524

**Comment by afc163** [comment]
Could you add test case?

**Comment by wmzhong** [comment]
I'd love to. However, I can't run the `npm run test` to verify my test case even I add my test case.

Could you help me for that?
Here's the log error.

image

**Comment by afc163** [comment]
What is the version of node.

**Comment by wmzhong** [comment]
V8.9.1

**Comment by afc163** [comment]
https://stackoverflow.com/a/46245846/3040605

**Comment by wmzhong** [comment]
@afc163 Test case is added.

**Pull request merged**
