### PR TITLE
Turkish translation

### LINKED ISSUE #123: need tr_TR support in locale
related to [https://github.com/ant-design/ant-design/issues/9373](https://github.com/ant-design/ant-design/issues/9373)

### PR DESCRIPTION
**Pull request by codesignist**
Fixes #123

### CODE REVIEW

**Comment by yesmeck** [comment]
You should use ES6 module, see https://github.com/react-component/pagination/blob/master/src/locale/en_US.js

**Comment by codesignist** [comment]
@yesmeck First I had copied en_US from my local. That's why I've made mistake. Sorry about that.
I've changed it now.

**Comment by yesmeck** [comment]
Thanks!

**Comment by codesignist** [comment]
Thank you. You are so fast.

What about updating npm package?
https://www.npmjs.com/package/rc-pagination

**Comment by yesmeck** [comment]
`rc-pagination@1.15.2`

**Pull request merged**
