### PR TITLE
Add locale es_ES (Spanish)

### PR DESCRIPTION
**Pull request by ginodeis**
I added Spanish locale (es_ES).

### CODE REVIEW

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/pull/5900

**Comment by paranoidjk** [comment]
@benjycui I do not have owner permission

**Comment by paranoidjk** [comment]
cc @afc163

**Comment by afc163** [comment]
```
npm owner ls rc-pagination
afc163 <afc163@gmail.com>
ibigbug <xiaobayuwei@gmail.com>
paranoidjk <hust2012jiangkai@gmail.com>
yiminghe <yiminghe@gmail.com>
```

**Comment by paranoidjk** [comment]
@ginodeis @benjycui released in 1.8.6

**Pull request merged**
