### PR TITLE
Create fa_IR.js

### PR DESCRIPTION
**Pull request by farskid**
Created locale of Farsi/Persian language

### CODE REVIEW

**Comment by paranoidjk** [comment]
@farskid  `rc-pagiantion@1.9.7`

**Comment by farskid** [comment]
@paranoidjk Should I update the PR?

**Comment by paranoidjk** [comment]
@farskid nope. I am just to tell you that your pr have been released at `rc-pagiantion@1.9.7.`

**Comment by farskid** [comment]
@paranoidjk OK, my bad :)

**Pull request merged**
