### PR TITLE
feat: extends showSizeChanger prop

### PR DESCRIPTION
**Pull request by jacklee814**
[#46070](https://github.com/ant-design/ant-design/pull/46070)

### CODE REVIEW

**Comment by Wxh16144** [comment]
这应该需要补充一份测试用例？

**Comment by afc163** [comment]
覆盖率掉了

**Comment by jacklee814** [comment]
我來補上測試

**Comment by jacklee814** [comment]
我等這個 merge 吧
https://github.com/react-component/pagination/pull/539

**Pull request closed without merging**
