### PR TITLE
add en-GB / it-IT / nl-BE locales

### PR DESCRIPTION
**Pull request by damiangreen**

### CODE REVIEW

**Comment by paranoidjk** [comment]
https://msdn.microsoft.com/en-us/library/ee825488(v=cs.20).aspx

**Comment by damiangreen** [comment]
@paranoidjk Any chance of bumping t he package version up by 1 as then I can do a pull request on the antD  parent library. thanks!

**Comment by paranoidjk** [comment]
already bumped version，look the master branch

**Comment by paranoidjk** [comment]
@damiangreen sorry, i forget it. I will do it right now.

**Comment by paranoidjk** [comment]
@damiangreen 1.9.2

**Comment by damiangreen** [comment]
brilliant! thanks

**Pull request merged**
