### PR TITLE
pass allPages to itemRender

### PR DESCRIPTION
**Pull request by zation**
So that I can use it to detect if current page is the last page

### CODE REVIEW

**Comment by benjycui** [comment]
Nope, just:

```jsx
const allPages
<Pagination itemRender={() => allPages} />
```

**Comment by zation** [comment]
@benjycui allPages is already calculated by Pagination, I don't want to write same code to calculate it again...

**Comment by benjycui** [comment]
Sorry, it's weirdo to let pagination tell you something you told it before.

**Comment by zation** [comment]
The calculation logic happens inside pagination. Users only tell pagination the total account and page size, but not the calculation logic. So I actually don't know what the allPages should be.

If pagination provides `allPagesCalculator` prop, it makes sense that pagination should not tell me what allPages is. But...

In another side, this will be more convenient to use itemRender and more consistent for allPages value.

**Pull request closed without merging**
